# Generated by Django 4.2.7 on 2024-01-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0004_rename_bike_cycle_bike_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='brake_rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='ブレーキ'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='frame_rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='フレーム'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='gire_rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='ギア'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='price_rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='値段'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='weight_rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='重さ'),
        ),
    ]
