# Generated by Django 4.2.7 on 2024-01-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='text',
            new_name='bike_name',
        ),
        migrations.AddField(
            model_name='cycle',
            name='bike',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
