# Generated by Django 4.2.7 on 2024-01-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_rename_text_cycle_bike_name_cycle_bike_cycle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='brake_rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='frame_rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='gire_rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='price_rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='weight_rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1),
            preserve_default=False,
        ),
    ]
