# Generated by Django 4.2.7 on 2024-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0005_alter_cycle_brake_rate_alter_cycle_frame_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
