# Generated by Django 4.2.7 on 2024-01-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0006_cycle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bike_thumnail', models.ImageField(upload_to='')),
                ('bike_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='値段')),
                ('weight_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='重さ')),
                ('strength_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='強度')),
            ],
        ),
    ]
