# Generated by Django 4.2.7 on 2024-01-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0007_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bike_thumnail', models.ImageField(upload_to='')),
                ('bike_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='値段')),
                ('weight_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='重さ')),
                ('tire_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='タイヤ幅')),
            ],
        ),
    ]
