# Generated by Django 4.2.7 on 2024-01-29 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0013_rename_review_id_cyclereview_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('thumnail', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('price_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='値段')),
                ('seinou_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='性能')),
                ('taikyu_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='耐久性')),
            ],
        ),
        migrations.CreateModel(
            name='Hundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('thumnail', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('price_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='値段')),
                ('haba_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='幅')),
                ('drop_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='ドロップ')),
            ],
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('thumnail', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('price_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='値段')),
                ('menseki_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='面積')),
                ('weight_rate', models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, verbose_name='軽さ')),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycle.brake')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycle.frame')),
                ('hundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycle.hundle')),
                ('pedal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycle.pedal')),
                ('wheel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycle.wheel')),
            ],
        ),
    ]
